CREATE TABLE IF NOT EXISTS arbitrage_opportunities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  symbol VARCHAR(32) NOT NULL,
  token_id BIGINT UNSIGNED NULL,
  chain VARCHAR(32) NOT NULL,
  contract_address VARCHAR(128) NOT NULL,
  direction VARCHAR(32) NOT NULL,
  trade_size_usd DECIMAL(30, 10) NOT NULL,
  binance_bid DECIMAL(30, 18) NULL,
  binance_ask DECIMAL(30, 18) NULL,
  binance_vwap DECIMAL(30, 18) NULL,
  dex_input_amount DECIMAL(50, 0) NULL,
  dex_output_amount DECIMAL(50, 0) NULL,
  dex_effective_price DECIMAL(30, 18) NULL,
  dex_price_impact DECIMAL(30, 18) NULL,
  gross_profit_usd DECIMAL(30, 10) NOT NULL,
  gross_spread_pct DECIMAL(30, 18) NOT NULL,
  estimated_cost_usd DECIMAL(30, 10) NOT NULL,
  net_profit_usd DECIMAL(30, 10) NOT NULL,
  net_spread_pct DECIMAL(30, 18) NOT NULL,
  quote_latency_ms INT UNSIGNED NULL,
  route_json JSON NULL,
  status ENUM('OPEN', 'UPDATED', 'CLOSED') NOT NULL DEFAULT 'OPEN',
  first_seen_at TIMESTAMP(3) NOT NULL,
  last_seen_at TIMESTAMP(3) NOT NULL,
  duration_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_opportunities_symbol_created (symbol, created_at),
  KEY idx_opportunities_net_spread (net_spread_pct, created_at),
  KEY idx_opportunities_first_seen (first_seen_at),
  KEY idx_opportunities_direction_created (direction, created_at),
  CONSTRAINT fk_opportunity_token FOREIGN KEY (token_id) REFERENCES tokens (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS opportunity_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  opportunity_id BIGINT UNSIGNED NOT NULL,
  observed_at TIMESTAMP(3) NOT NULL,
  net_spread_pct DECIMAL(30, 18) NOT NULL,
  net_profit_usd DECIMAL(30, 10) NOT NULL,
  binance_price DECIMAL(30, 18) NULL,
  dex_price DECIMAL(30, 18) NULL,
  PRIMARY KEY (id),
  KEY idx_snapshots_opportunity_observed (opportunity_id, observed_at),
  CONSTRAINT fk_snapshot_opportunity FOREIGN KEY (opportunity_id) REFERENCES arbitrage_opportunities (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
